title: "Jack Haughey"
description: "My ongoing learning log for Kubernetes, Azure, and cloud‑native engineering. A simple Jekyll site where I document concepts, commands, patterns, and troubleshooting notes as I grow my skills."
markdown: kramdown
theme: null
hightlighter: rouge
